version: "3.8"
services:
  web-fe:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  redis:
    image: "gabriellathorne/teamoak"
    networks:
      - counter-net

networks:
  counter-net:

volumes:
  counter-vol:
