apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: team-oak
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 10
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
availabilityZones: ['us-east-1a', 'us-east-1b'] 