apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamoak-deployment
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
      - name: flask-app
        image: gabriellathorne/teamoak
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  selector:
    app: flask-app
  type: LoadBalancer  
  ports:
  - name: flask-app
    protocol: TCP
    port: 80
    targetPort: 5000       